api/config/routes.rb
Rails.application.routes.draw do
  root "articles#index"
  resources :articles, defaults: { format: :json }
end

api/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

api/app/models/article.rb
class Article < ApplicationRecord
  default_scope { order(created_at: :desc) }
  validates :title, presence: true
  validates :author, presence: true
  validates :body, presence: true, length: { minimum: 1 }
end

api/app/controllers/application_controller.rb
class ApplicationController < ActionController::API
  def render_by_content_type(data)
    if request.formats.include? 'application/json'
      render json: data
    end
  end
end

api/app/controllers/articles_controller.rb
class ArticlesController < ApplicationController
  def index
    @articles = Article.all
    render_by_content_type(@articles)
  end

  def show
    @article = Article.find(params[:id])
    render_by_content_type(@article)
  end

  def create
    @article = Article.new(article_params)
    @article.save
    render_by_content_type(@article)
  end

  def update
    @article = Article.find(params[:id])
    @article.update! article_params
    render_by_content_type(@article)
  end

  def destroy
    @article = Article.find(params[:id])
    @article.destroy
    render_by_content_type(@article)
  end

  private

  def article_params
    params.require(:article).permit(:title, :author, :body)
  end
end

api/app/helpers/application_helper.rb
module ApplicationHelper
end

api/app/helpers/articles_helper.rb
module ArticlesHelper
end

api/app/views/articles/index.html.erb
<h2>Articles</h2>

<p>
  <%= link_to 'New Article', new_article_path %>
</p>

<% if @articles.length > 0  %>
  <ul>
    <% @articles.each do |article| %>
      <li>
        <%= link_to article.title, article %>
        <i>by <%= article.author %></i>
      </li>
    <% end %>
  </ul>
<% else %>
  <p class="notice">No articles found.</p>
<% end %>

api/app/views/articles/new.html.erb
<h2>Add Article</h2>

<form action="/articles" accept-charset="UTF-8" method="post">
  <input type="hidden" name="authenticity_token" value="...">

  <div>
    <label for="article_title">Title</label><br>
    <input type="text" name="article[title]" id="article_title" value="<% @article.author %>">
  </div>

  <div>
    <label for="article_author">Author</label><br>
    <input type="text" name="article[author]" id="article_author" value="<% @article.author %>">
  </div>

  <div>
    <label for="article_body">Body</label><br>
    <textarea name="article[body]" id="article_body">
      <%= @article.body %>
    </textarea>
  </div>

  <div>
    <input type="submit" name="commit" value="Save" data-disable-with="Save">
  </div>
</form>

api/app/views/articles/show.html.erb
<h2><%= @article.title %></h2>

<p>
  <i><%= @article.author %></i>
</p>

<p>
  <%= @article.body %>
</p>

<p>
  <%= link_to "Delete Article",
              article_path(@article),
              method: :delete,
              data: { confirm: "Are you sure?" }
  %>
</p>

api/app/views/layouts/application.html.erb
<!DOCTYPE html>

<html>
<head>
  <title>Blarg</title>
  <meta name="viewport" content="width=device-width,initial-scale=1">
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
<header>
  <h1><%= link_to 'Blarg', root_path %></h1>
</header>

<nav>
  <ul>
    <li><%= link_to 'Home', root_path %></li>
    <li><%= link_to 'Articles', articles_path %></li>
  </ul>
</nav>

<main>
  <%= yield %>
</main>
</body>
</html>